export const GET_INITIAL_STATE = 'GET_INITIAL_STATE';

export const CHANGE_DS_CHECKBOX = 'CHANGE_DS_CHECKBOX';
export const CHANGE_DB_CHECKBOX = 'CHANGE_DB_CHECKBOX';
export const CHANGE_WEB_CHECKBOX = 'CHANGE_WEB_CHECKBOX';
